name: Versioner CI

on:
  # push:
  #   branches: [master]
  # pull_request:

  push:
    branches:
      - master

  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.3'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - name: Install shards
        run: shards install
      - name: Format

        run: crystal tool format --check
      - name: Lint
        run: ./bin/ameba
