name: Versioner CI

on:
  # push:
  #   branches: [master]
  # pull_request:

  push:
    branches:
      - master

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - name: Install shards
        run: shards install
      # - name: Format
      # 
      #   run: crystal tool format --check
      # - name: Lint
      #   run: ./bin/ameba

