name: Crystal CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches:
      - '**' # This wildcard also matches all branches for pull requests

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
